[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0" 

baseURL = "https://saurabhkankriya.github.io/"
languageCode = 'en-us'
title = 'Saurabh Jain'
theme = 'hugo-noir'

# URL handling
relativeURLs = false
canonifyURLs = true

# Multilingual configuration
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
[params]
  name = "Saurabh Jain"
  location = "Pune, India"
  description = "Description ..."
  profile_image = "/images/your-profile.jpg" # Place in your site's static/images/
  # Social links
  github = "https://github.com/saurabhkankriya"
  twitter = "https://twitter.com/saurabhkankriya"
  linkedin = "https://www.linkedin.com/in/saurabhkankriya/"
  # email = "your.email@example.com"
  # ... other params ...

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 5
