[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0" 

baseURL = "https://saurabhkankriya.github.io/"
languageCode = 'en-us'
title = 'Saurabh Jain'

# URL handling
relativeURLs = false
canonifyURLs = true

# Multilingual configuration
defaultContentLanguage = "en"
[params]
  name = "Saurabh Jain"
  location = "Pune, India"
  description = "Customer-focused Generative AI Engineer with 10+ years of experience in software development and AI, specializing in building intelligent systems that solve real-world business problems."
  profile_image = "/images/your-profile.jpg" # Place in your site's static/images/
  # Social links
  github = "https://github.com/saurabhkankriya"
  twitter = "https://twitter.com/saurabhkankriya"
  linkedin = "https://www.linkedin.com/in/saurabhkankriya/"
  # email = "your.email@example.com"
  
  # Chatbot configuration
  chatbot_enabled = true
  chatbot_agent_id = "68a2032ada94f86e35e1602a"
  chatbot_user_id = "saurabhgithub@gmail.com"
  chatbot_session_id = "68a2032ada94f86e35e1602a-nvrutcc2pnj"
  # ... other params ...

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^LYZR_API_KEY$']

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 5
